// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_follower
global.__objectDepths[1] = 0; // ctrl_main
global.__objectDepths[2] = 0; // input
global.__objectDepths[3] = 0; // par_solid
global.__objectDepths[4] = 0; // par_solid_blue
global.__objectDepths[5] = 0; // par_solid_red
global.__objectDepths[6] = 0; // obj_wall
global.__objectDepths[7] = 0; // obj_solid
global.__objectDepths[8] = 0; // obj_semisolid
global.__objectDepths[9] = 0; // par_wall
global.__objectDepths[10] = 0; // climb
global.__objectDepths[11] = 0; // obj_player
global.__objectDepths[12] = 0; // Spawn
global.__objectDepths[13] = 0; // par_enemy
global.__objectDepths[14] = 0; // obj_goomba
global.__objectDepths[15] = 0; // spike_obj
global.__objectDepths[16] = 0; // spike1_obj
global.__objectDepths[17] = 0; // spike2_obj
global.__objectDepths[18] = 0; // spike3_obj
global.__objectDepths[19] = 0; // Flandre_obj
global.__objectDepths[20] = 0; // obj_brick
global.__objectDepths[21] = 0; // obj_brick_mushroom
global.__objectDepths[22] = 0; // obj_brick_inf_coin
global.__objectDepths[23] = 0; // obj_brick_star
global.__objectDepths[24] = 0; // obj_block_coin
global.__objectDepths[25] = 0; // obj_block_mushroom
global.__objectDepths[26] = 0; // obj_invisible_1up
global.__objectDepths[27] = 0; // Carry
global.__objectDepths[28] = 0; // DirRight_obj
global.__objectDepths[29] = 0; // DirLeft_obj
global.__objectDepths[30] = 0; // DirUp_obj
global.__objectDepths[31] = 0; // DirDown_obj
global.__objectDepths[32] = -2; // obj_holdparent
global.__objectDepths[33] = 0; // PalladiumBlock_obj
global.__objectDepths[34] = 0; // obj_mushroom
global.__objectDepths[35] = 0; // obj_1up
global.__objectDepths[36] = 0; // obj_star
global.__objectDepths[37] = -1; // obj_inf_coin
global.__objectDepths[38] = 0; // Menu
global.__objectDepths[39] = 0; // GridBoot
global.__objectDepths[40] = 0; // BootTitle
global.__objectDepths[41] = 0; // TextDrawBIOS
global.__objectDepths[42] = 0; // AnimatedTileGrav
global.__objectDepths[43] = 0; // GridBootAnim
global.__objectDepths[44] = 0; // TilePal
global.__objectDepths[45] = 0; // TileGamePal
global.__objectDepths[46] = 0; // TitleBGPal
global.__objectDepths[47] = 0; // MenuPal_obj
global.__objectDepths[48] = 999999; // BGPal
global.__objectDepths[49] = 0; // RoomSkipper
global.__objectDepths[50] = 0; // MusicPlayer
global.__objectDepths[51] = 0; // WinCenter
global.__objectDepths[52] = 0; // CamMove
global.__objectDepths[53] = 0; // CamScroll
global.__objectDepths[54] = 0; // RoomNameTitle
global.__objectDepths[55] = 0; // RoomTransition
global.__objectDepths[56] = 0; // updownscrolling
global.__objectDepths[57] = 0; // updownscrolling2
global.__objectDepths[58] = 0; // obj_gme
global.__objectDepths[59] = 0; // obj_gme_demo
global.__objectDepths[60] = 0; // SettingsMenu
global.__objectDepths[61] = 0; // WindowMenu
global.__objectDepths[62] = 0; // MainMenu
global.__objectDepths[63] = 0; // GraphicsMenu
global.__objectDepths[64] = 0; // MenuTest
global.__objectDepths[65] = 0; // obj_CRT_Windows
global.__objectDepths[66] = 0; // obj_CRT_HTML5
global.__objectDepths[67] = 0; // obj_monochrome
global.__objectDepths[68] = 0; // obj_gameboy
global.__objectDepths[69] = 0; // obj_default
global.__objectDepths[70] = 0; // GravWallUp_obj
global.__objectDepths[71] = 0; // GravWallDown_obj
global.__objectDepths[72] = 0; // obj_palette_manager
global.__objectDepths[73] = 0; // obj_tile_swapper_start
global.__objectDepths[74] = 0; // obj_tile_swapper_end
global.__objectDepths[75] = 0; // GravScreenDown_obj
global.__objectDepths[76] = 0; // GravScreenUp_obj
global.__objectDepths[77] = 0; // SwirchBlockBlue_obj
global.__objectDepths[78] = 0; // SwitchBlockRed_obj
global.__objectDepths[79] = 0; // Lever_obj
global.__objectDepths[80] = 0; // GlobalIniHypervisor
global.__objectDepths[81] = 0; // FontLoader
global.__objectDepths[82] = 0; // obj_beepblock_red
global.__objectDepths[83] = 0; // obj_beepblock_blue
global.__objectDepths[84] = 0; // OrangeBeepBlock_OBJ
global.__objectDepths[85] = 0; // GreenBeepBlock_OBJ
global.__objectDepths[86] = 0; // MovPlatH_obj
global.__objectDepths[87] = 0; // LinePlatH_obj
global.__objectDepths[88] = 0; // obj_path_hor
global.__objectDepths[89] = 0; // obj_path_ver
global.__objectDepths[90] = 0; // obj_path_circle_b3
global.__objectDepths[91] = 0; // obj_path_circle_b2
global.__objectDepths[92] = 0; // obj_path_circle_b1
global.__objectDepths[93] = 0; // obj_path_circle_b4
global.__objectDepths[94] = 0; // obj_pathparent
global.__objectDepths[95] = 0; // obj_blocktrain_killer
global.__objectDepths[96] = 0; // obj_blocktrain
global.__objectDepths[97] = -1; // obj_blocktrain_back
global.__objectDepths[98] = 1; // obj_blocktrain_middle
global.__objectDepths[99] = -1; // obj_blocktrain_front
global.__objectDepths[100] = 0; // GravWallLeft_obj
global.__objectDepths[101] = 0; // LineH_obj
global.__objectDepths[102] = 0; // LineV_obj
global.__objectDepths[103] = 0; // GravWallRight_obj
global.__objectDepths[104] = 0; // door3_1_obj
global.__objectDepths[105] = 0; // key_obj
global.__objectDepths[106] = 0; // Discord
global.__objectDepths[107] = 0; // checkpoint_obj


global.__objectNames[0] = "obj_follower";
global.__objectNames[1] = "ctrl_main";
global.__objectNames[2] = "input";
global.__objectNames[3] = "par_solid";
global.__objectNames[4] = "par_solid_blue";
global.__objectNames[5] = "par_solid_red";
global.__objectNames[6] = "obj_wall";
global.__objectNames[7] = "obj_solid";
global.__objectNames[8] = "obj_semisolid";
global.__objectNames[9] = "par_wall";
global.__objectNames[10] = "climb";
global.__objectNames[11] = "obj_player";
global.__objectNames[12] = "Spawn";
global.__objectNames[13] = "par_enemy";
global.__objectNames[14] = "obj_goomba";
global.__objectNames[15] = "spike_obj";
global.__objectNames[16] = "spike1_obj";
global.__objectNames[17] = "spike2_obj";
global.__objectNames[18] = "spike3_obj";
global.__objectNames[19] = "Flandre_obj";
global.__objectNames[20] = "obj_brick";
global.__objectNames[21] = "obj_brick_mushroom";
global.__objectNames[22] = "obj_brick_inf_coin";
global.__objectNames[23] = "obj_brick_star";
global.__objectNames[24] = "obj_block_coin";
global.__objectNames[25] = "obj_block_mushroom";
global.__objectNames[26] = "obj_invisible_1up";
global.__objectNames[27] = "Carry";
global.__objectNames[28] = "DirRight_obj";
global.__objectNames[29] = "DirLeft_obj";
global.__objectNames[30] = "DirUp_obj";
global.__objectNames[31] = "DirDown_obj";
global.__objectNames[32] = "obj_holdparent";
global.__objectNames[33] = "PalladiumBlock_obj";
global.__objectNames[34] = "obj_mushroom";
global.__objectNames[35] = "obj_1up";
global.__objectNames[36] = "obj_star";
global.__objectNames[37] = "obj_inf_coin";
global.__objectNames[38] = "Menu";
global.__objectNames[39] = "GridBoot";
global.__objectNames[40] = "BootTitle";
global.__objectNames[41] = "TextDrawBIOS";
global.__objectNames[42] = "AnimatedTileGrav";
global.__objectNames[43] = "GridBootAnim";
global.__objectNames[44] = "TilePal";
global.__objectNames[45] = "TileGamePal";
global.__objectNames[46] = "TitleBGPal";
global.__objectNames[47] = "MenuPal_obj";
global.__objectNames[48] = "BGPal";
global.__objectNames[49] = "RoomSkipper";
global.__objectNames[50] = "MusicPlayer";
global.__objectNames[51] = "WinCenter";
global.__objectNames[52] = "CamMove";
global.__objectNames[53] = "CamScroll";
global.__objectNames[54] = "RoomNameTitle";
global.__objectNames[55] = "RoomTransition";
global.__objectNames[56] = "updownscrolling";
global.__objectNames[57] = "updownscrolling2";
global.__objectNames[58] = "obj_gme";
global.__objectNames[59] = "obj_gme_demo";
global.__objectNames[60] = "SettingsMenu";
global.__objectNames[61] = "WindowMenu";
global.__objectNames[62] = "MainMenu";
global.__objectNames[63] = "GraphicsMenu";
global.__objectNames[64] = "MenuTest";
global.__objectNames[65] = "obj_CRT_Windows";
global.__objectNames[66] = "obj_CRT_HTML5";
global.__objectNames[67] = "obj_monochrome";
global.__objectNames[68] = "obj_gameboy";
global.__objectNames[69] = "obj_default";
global.__objectNames[70] = "GravWallUp_obj";
global.__objectNames[71] = "GravWallDown_obj";
global.__objectNames[72] = "obj_palette_manager";
global.__objectNames[73] = "obj_tile_swapper_start";
global.__objectNames[74] = "obj_tile_swapper_end";
global.__objectNames[75] = "GravScreenDown_obj";
global.__objectNames[76] = "GravScreenUp_obj";
global.__objectNames[77] = "SwirchBlockBlue_obj";
global.__objectNames[78] = "SwitchBlockRed_obj";
global.__objectNames[79] = "Lever_obj";
global.__objectNames[80] = "GlobalIniHypervisor";
global.__objectNames[81] = "FontLoader";
global.__objectNames[82] = "obj_beepblock_red";
global.__objectNames[83] = "obj_beepblock_blue";
global.__objectNames[84] = "OrangeBeepBlock_OBJ";
global.__objectNames[85] = "GreenBeepBlock_OBJ";
global.__objectNames[86] = "MovPlatH_obj";
global.__objectNames[87] = "LinePlatH_obj";
global.__objectNames[88] = "obj_path_hor";
global.__objectNames[89] = "obj_path_ver";
global.__objectNames[90] = "obj_path_circle_b3";
global.__objectNames[91] = "obj_path_circle_b2";
global.__objectNames[92] = "obj_path_circle_b1";
global.__objectNames[93] = "obj_path_circle_b4";
global.__objectNames[94] = "obj_pathparent";
global.__objectNames[95] = "obj_blocktrain_killer";
global.__objectNames[96] = "obj_blocktrain";
global.__objectNames[97] = "obj_blocktrain_back";
global.__objectNames[98] = "obj_blocktrain_middle";
global.__objectNames[99] = "obj_blocktrain_front";
global.__objectNames[100] = "GravWallLeft_obj";
global.__objectNames[101] = "LineH_obj";
global.__objectNames[102] = "LineV_obj";
global.__objectNames[103] = "GravWallRight_obj";
global.__objectNames[104] = "door3_1_obj";
global.__objectNames[105] = "key_obj";
global.__objectNames[106] = "Discord";
global.__objectNames[107] = "checkpoint_obj";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for